### ISSUE TITLE
Not compatible with dplyr 0.5.0

### ISSUE THREAD

**Issue by hannesroos** [vertica/vertica.dplyr#17]
When installed the latest version of vertica.dplyr, which also automatically updated dplyr to 0.5.0, it gave the following error: 

```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'sql_set_op.DBIConnection' not found
```

After loading vertica.dplyr to library, it gave this error:

```
Error : object 'src_translate_env' not found whilst loading namespace 'vertica.dplyr'
Error: package or namespace load failed for ‘vertica.dplyr’
```

However, when I downgraded dplyr to 0.4.3, it continues to work. I guess the issue is that dplyr is not backwards compatible. Regardless, are you aware of the issue and are there plans to fix it in the near future?

**Comment by etduwx** [comment]
Hi @hannesroos ,

Yes, we are aware of this issue and are working on it actively.

Thanks for your patience.

**Comment by hannesroos** [comment]
Hi @etduwx,
thanks for that. I got the latest version of vertica.dplyr from github today, and it did load after automatically updating dplyr to 0.5.0. I also managed to connect to my DWH using src_vertica. When I tried to load a table with tbl, it did give the following error:

`Error in sqlQuery(conn, query) : 
  first argument is not an open vRODBC channel`

When I downgraded dplyr to 0.4.3, vertica.dplyr did not load anymore and gave this error:

`Loading required package: assertthat
Loading required package: dplyr

Attaching package: �dplyr�

The following objects are masked from �package:stats�:

```
filter, lag
```

The following objects are masked from �package:base�:

```
intersect, setdiff, setequal, union
```

Error : object 'db_create_indexes' not found whilst loading namespace 'vertica.dplyr'
Error: package or namespace load failed for ‘vertica.dplyr’`

I have the older version of vertica.dplyr in backup so I can go back to that. Regardless, is that issue on my end or is the latest version of vertica.dplyr still incompatible with the latest version of dplyr?

**Comment by etduwx** [comment]
Hi @hannesroos , sorry for the issues that you are facing. Are you connecting with ODBC or JDBC? It may be that only ODBC is supported now. @vishrutg worked on v0.5+ compatibility, so perhaps he can comment.

Thanks,
Edward

**Comment by hannesroos** [comment]
Hi @edenzik, I'm connecting with ODBC. I finally got loading tables to work with using raw SQL inside tbl, eg:
`data <- tbl(vertica_odbc, sql("SELECT * FROM schema.table"))`
So for now the problem is solved.

Hannes

**Comment by etduwx** [comment]
Glad to hear it, @hannesroos . @vishrutg , could you take a look to see what was causing the original issue? This needs to be fixed.

Thanks.

**Comment by shearerpmm** [comment]
I'm using JDBC and dplyr 0.5.0 - and neither tbl nor the sql trick work:

```
vj <- src_vertica(...)
gbs = vj %>% tbl(sql('select * from mytable'))
```

Result:

> Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
>   Unable to retrieve JDBC result set for SELECT \* FROM (select \* from mytable) AS FOO WHERE 0=1 ([Vertica][VJDBC](4566) ERROR: Relation "mytable" does not exist)

If I type vj at the R prompt, mytable is in the list of tbls, so it's there and recognized but I can't select from it.

**Comment by etduwx** [comment]
Hi guys, 

I am sorry you are experiencing all of these issues. We will look into it ASAP.

Until then, hopefully one acceptable workaround is to downgrade to dplyr 0.4.3, pull the previous version of vertica.dplyr, and use that.

Thank you.

**Comment by hhoeflin** [comment]
I wanted to check if this is an open issue or fixed by the large merge?

Thanks

**Comment by sstreisand** [comment]
It was not fixed for me.  I am currently experiencing this issue using JDBC using dplyr 0.5.0 and vertica.dplyr ‘0.4.2’.  So does it work if I go back to dplyr  0.4.3?

**Comment by hannesroos** [comment]
I currently do not use vertica.dplyr because of said issues. I use [RJDBC](https://www.rforge.net/RJDBC/) and regular dplyr instead.

The code I use to connect to my database looks something like that:

> dr <- JDBC("com.vertica.jdbc.Driver", classPath = "~/vertica/vertica.jar")
conn <- dbConnect(dr, "jdbc:vertica://url:5433/database_name?user=username&password=password")

Hope that helps!

**Comment by sstreisand** [comment]
Thanks @hannesroos - I need to use the vertica bulk copy command (copy_to) and I don't know another way to do that from R.  Does RJDBC support that command?  I've actually gotten copy_to to work sort of.  It writes the data successfully but gives an error on the return, so if I put it in a tryCatch block and there was no other error, it will work.

`tryCatch({results <- copy_to(vertica, dfToWrite, dname)}, error=function(e) {
       print(paste('e:',e));
       print("Might still have been written")}) `

Where my dname is `dname <- paste0("'",dschema,"'", ".", '"', dname, '"')`
so each piece is explicitly quoted.
